export const SEED_CITIES = [
  'Parwanoo',
  'Chandigarh',
  'Mohali',
  'Panchkula',
  'Kalka',
  'Pinjore',
  'Baddi',
  'Shimla',
  'Solan',
  'Zirakpur',
] as const;

export const SEED_USERS = [
  // --- Admin ---
  {
    name: 'Sharad Admin',
    email: 'sharad@admin.com',
    password: 'Password123!',
    phone: '+917590889608',
    city: 'Parwanoo',
    role: 'ADMIN' as const,
    avatarUrl: 'https://iili.io/CrWkLAl.png',
  },

  // --- 5 Dedicated Mock Customer Users ---
  {
    name: 'Test Customer',
    email: 'user@test.com',
    password: 'Password123!',
    phone: '+919999999999',
    city: 'Chandigarh',
    role: 'USER' as const,
    avatarUrl: 'https://iili.io/C4rpldN.png',
  },
  {
    name: 'Saksham Client',
    email: 'saksham.client@gmail.com',
    password: 'Password123!',
    phone: '+919877777777',
    city: 'Mohali',
    role: 'USER' as const,
    avatarUrl: 'https://iili.io/C4iBYU7.png',
  },
  {
    name: 'Sneha Sharma',
    email: 'sneha.customer@gmail.com',
    password: 'Password123!',
    phone: '+919888888888',
    city: 'Panchkula',
    role: 'USER' as const,
    avatarUrl: 'https://iili.io/C4iFVae.png',
  },
  {
    name: 'Rohit Sharma',
    email: 'rohit.buyer@gmail.com',
    password: 'Password123!',
    phone: '+919899999999',
    city: 'Parwanoo',
    role: 'USER' as const,
    avatarUrl: 'https://iili.io/C4iBGxj.png',
  },
  {
    name: 'Simran Sharma',
    email: 'simran.sharma@gmail.com',
    password: 'Password123!',
    phone: '+919711111111',
    city: 'Solan',
    role: 'USER' as const,
    avatarUrl: 'https://iili.io/C4iKoAb.png',
  },

  // --- Complete Unified Worker List ---
  {
    name: 'Smarth Sharda',
    email: 'smarth.sharda@chowkspot.com',
    category: 'Electrician',
    bio: 'Hello, I am Smarth Sharda with over 5 years of hands-on experience in residential and commercial electrical systems. I specialize in complete home inverter wiring, smart switch automation, heavy-load MCB board upgrades, and fault troubleshooting. I take pride in offering transparent pricing, adhering strictly to safety regulations, and leaving your space spotless after every job.',
    experienceYears: 5,
    rateType: 'HOURLY' as const,
    baseRate: '400.00',
    isAvailable: true,
    serviceCities: ['Chandigarh', 'Mohali', 'Panchkula', 'Kalka', 'Parwanoo'],
    paymentIdentifier: 'smarthsharda14@oksbi',
    password: 'Password123!',
    phone: '+919811111111',
    city: 'Chandigarh',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrGINTu.png',
  },
  {
    name: 'Rudar Partap Singh',
    email: 'rudar.partap@chowkspot.com',
    category: 'Plumber',
    bio: 'Greetings! I am Rudar Partap Singh, a licensed professional plumber with 6+ years of expertise. From high-pressure pipe leak detections and underground leakage repairs to complete bathroom sanitary installations and overhead water tank cleanings, I handle it all. Count on me for prompt arrival, durable fittings, and completely fair peer-to-peer settlement rates.',
    experienceYears: 6,
    rateType: 'FIXED' as const,
    baseRate: '600.00',
    isAvailable: true,
    serviceCities: ['Mohali', 'Chandigarh', 'Panchkula', 'Zirakpur'],
    paymentIdentifier: '8168535087@kotak811',
    password: 'Password123!',
    phone: '+919822222222',
    city: 'Mohali',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrGAm3Q.png',
  },
  {
    name: 'Mohit Thakur',
    email: 'mohit.thakur@chowkspot.com',
    category: 'Carpenter',
    bio: 'I am Mohit Thakur, an expert craftsman specializing in custom modular furniture assembly, wardrobe sliding track repairs, wooden flooring adjustments, and emergency door lock replacements. With 4 years in the trade, I focus on precision joinery and sturdy finishes that stand the test of time.',
    experienceYears: 4,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '250.00',
    isAvailable: true,
    serviceCities: ['Parwanoo', 'Kalka', 'Pinjore', 'Solan'],
    paymentIdentifier: '8307823497@ibl',
    password: 'Password123!',
    phone: '+919833333333',
    city: 'Parwanoo',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrGYVoX.png',
  },
  {
    name: 'Bipin Awasthi',
    email: 'bipin.awasthi@chowkspot.com',
    category: 'Home Appliance Repair',
    bio: 'With 7 years of dedicated experience, I am Bipin Awasthi, your trusted local specialist for home appliance maintenance. I expertly manage washing machine drum motor replacements, microwave control board fixes, and refrigerator gas charging. Quality workmanship and honest troubleshooting are my core guarantees.',
    experienceYears: 7,
    rateType: 'FIXED' as const,
    baseRate: '750.00',
    isAvailable: true,
    serviceCities: ['Kalka', 'Parwanoo', 'Panchkula', 'Pinjore'],
    paymentIdentifier: 'bipinawasthi2004@okaxis',
    password: 'Password123!',
    phone: '+919844444444',
    city: 'Kalka',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrGcljI.png',
  },
  {
    name: 'Anshul Katoch',
    email: 'anshul.katoch@chowkspot.com',
    category: 'Painter',
    bio: 'I am Anshul Katoch, a professional interior and exterior painting contractor with 5 years of experience. I specialize in dampness treatment, wall waterproofing, Royal texture coatings, and flawless putty finishes. I ensure proper furniture masking and clean up every trace of work before handover.',
    experienceYears: 5,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '300.00',
    isAvailable: true,
    serviceCities: ['Shimla', 'Solan', 'Kandaghat', 'Parwanoo'],
    paymentIdentifier: 'anshul.katoch@upi',
    password: 'Password123!',
    phone: '+919855555555',
    city: 'Shimla',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrMDZrl.th.png',
  },
  {
    name: 'Anshul Thakur',
    email: 'anshul.thakur@chowkspot.com',
    category: 'Car Mechanic',
    bio: 'Hello, I am Anshul Thakur, providing on-demand 4-wheeler and car breakdown support across the hill and valley belt. With 6 years of experience, I handle emergency battery jumpstarts, brake tuning, suspension checks, and timely oil changes right at your location.',
    experienceYears: 6,
    rateType: 'HOURLY' as const,
    baseRate: '500.00',
    isAvailable: true,
    serviceCities: ['Solan', 'Parwanoo', 'Dharampur', 'Kalka'],
    paymentIdentifier: 'anshul.thakur@sbi',
    password: 'Password123!',
    phone: '+919866666666',
    city: 'Solan',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C449TiJ.md.jpg',
  },
  {
    name: 'Rohan Chandel',
    email: 'rohan.chandel@chowkspot.com',
    category: 'Generator Mechanic',
    bio: 'I am Rohan Chandel, an industrial generator and backup power specialist with 6 years of field experience. I handle heavy diesel generator overhauls, motor starter repairs, and factory-grade backup electrical wiring with uncompromising technical accuracy.',
    experienceYears: 6,
    rateType: 'HOURLY' as const,
    baseRate: '650.00',
    isAvailable: true,
    serviceCities: ['Baddi', 'Nalagarh', 'Parwanoo', 'Barotiwala'],
    paymentIdentifier: 'rohan.chandel@icici',
    password: 'Password123!',
    phone: '+919812121212',
    city: 'Baddi',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrVuhss.md.jpg',
  },
  {
    name: 'Kartik Kumar',
    email: 'kartik.kumar@chowkspot.com',
    category: 'CCTV & Security Tech',
    bio: 'I am Kartik Kumar, a security systems technician with 4 years of experience setting up IP surveillance cameras, biometric access control, NVR configurations, and video doorbells for homes and commercial offices.',
    experienceYears: 4,
    rateType: 'FIXED' as const,
    baseRate: '800.00',
    isAvailable: true,
    serviceCities: ['Parwanoo', 'Kalka', 'Solan', 'Chandigarh'],
    paymentIdentifier: 'kartik.kumar@paytm',
    password: 'Password123!',
    phone: '+919834343434',
    city: 'Parwanoo',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44yu5B.md.jpg',
  },
  {
    name: 'Sahil Vashisht',
    email: 'sahil.vashisht@chowkspot.com',
    category: 'Plumber',
    bio: 'I am Sahil Vashisht, an active residential plumber focusing on geyser installations, RO water purifier servicing, pipeline fittings, and booster motor pump repairs. I ensure reliable water flow and leak-free joints every single time.',
    experienceYears: 3,
    rateType: 'FIXED' as const,
    baseRate: '350.00',
    isAvailable: true,
    serviceCities: ['Solan', 'Parwanoo', 'Shimla'],
    paymentIdentifier: 'sahil.vashisht@okaxis',
    password: 'Password123!',
    phone: '+919878787878',
    city: 'Solan',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrVzQdN.md.jpg',
  },
  {
    name: 'Sahil Akhtar',
    email: 'sahil.akhtar@chowkspot.com',
    category: 'Pest Control Specialist',
    bio: 'I am Sahil Akhtar, providing deep cleaning pest control solutions including kitchen degreasing, sofa shampooing, anti-termite borer treatment, and complete cockroach elimination using safe, odorless formulations.',
    experienceYears: 4,
    rateType: 'FIXED' as const,
    baseRate: '1200.00',
    isAvailable: true,
    serviceCities: ['Panchkula', 'Chandigarh', 'Mohali', 'Kalka'],
    paymentIdentifier: 'sahil.akhtar@ybl',
    password: 'Password123!',
    phone: '+919890909090',
    city: 'Panchkula',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrVdoSj.png',
  },
  {
    name: 'Tarun Kumawat',
    email: 'tarun.kumawat@chowkspot.com',
    category: 'Welder & Fabricator',
    bio: 'I am Tarun Kumawat, a skilled metal fabricator with 7 years of expertise in main security gate welding, balcony safety grill construction, tin shed roofing, and structural railing repairs.',
    experienceYears: 7,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '500.00',
    isAvailable: true,
    serviceCities: ['Baddi', 'Barotiwala', 'Nalagarh', 'Parwanoo'],
    paymentIdentifier: 'tarun.kumawat@upi',
    password: 'Password123!',
    phone: '+919712121212',
    city: 'Baddi',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C469BpI.jpg',
  },
  {
    name: 'Gagan Bansal',
    email: 'gagan.bansal@chowkspot.com',
    category: 'Masonry & Brickwork',
    bio: 'I am Gagan Bansal, a veteran mason with 8 years of experience in granite countertop fittings, bathroom tile replacements, wall plastering, and structural brickwork maintenance across regional project sites.',
    experienceYears: 8,
    rateType: 'HOURLY' as const,
    baseRate: '400.00',
    isAvailable: false,
    serviceCities: ['Kalka', 'Pinjore', 'Parwanoo', 'Panchkula'],
    paymentIdentifier: 'gagan.bansal@sbi',
    password: 'Password123!',
    phone: '+919734343434',
    city: 'Kalka',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrVFDb4.png',
  },
  {
    name: 'Sachit Rajpal',
    email: 'sachit.rajpal@chowkspot.com',
    category: 'Electrician',
    bio: 'Hello, I am Sachit Rajpal, an expert residential and commercial electrician with 6 years of professional practice. I specialize in complex circuit troubleshooting, inverter setups, and lighting automation. My focus is on absolute safety and clean workmanship.',
    experienceYears: 6,
    rateType: 'HOURLY' as const,
    baseRate: '450.00',
    isAvailable: true,
    serviceCities: ['Chandigarh', 'Mohali', 'Panchkula', 'Zirakpur'],
    paymentIdentifier: 'sachit.rajpal@upi',
    password: 'Password123!',
    phone: '+919877777777',
    city: 'Chandigarh',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44Jqj1.png',
  },
  {
    name: 'Safal Varadhan',
    email: 'safal.varadhan@chowkspot.com',
    category: 'Plumber',
    bio: 'I am Safal Varadhan, an expert plumber dedicated to resolving pipe bursts, bathroom sanitary fittings, and high-pressure water pump installations with 5 years of reliable field service.',
    experienceYears: 5,
    rateType: 'FIXED' as const,
    baseRate: '550.00',
    isAvailable: true,
    serviceCities: ['Mohali', 'Chandigarh', 'Zirakpur'],
    paymentIdentifier: 'safal.varadhan@upi',
    password: 'Password123!',
    phone: '+919888888888',
    city: 'Mohali',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C442yCX.md.jpg',
  },
  {
    name: 'Sachin Kumar Thakur',
    email: 'sachin.thakur@chowkspot.com',
    category: 'Carpenter',
    bio: 'I am Sachin Kumar Thakur, offering modular furniture assembly, wardrobe design, door lock installations, and customized wooden fixtures with 7 years of craftsmanship experience.',
    experienceYears: 7,
    rateType: 'HOURLY' as const,
    baseRate: '400.00',
    isAvailable: true,
    serviceCities: ['Panchkula', 'Chandigarh', 'Pinjore'],
    paymentIdentifier: 'sachin.thakur@upi',
    password: 'Password123!',
    phone: '+919899999999',
    city: 'Panchkula',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C443mHx.md.png',
  },
  {
    name: 'Shaiv Sood',
    email: 'shaiv.sood@chowkspot.com',
    category: 'Painter',
    bio: 'I am Shaiv Sood, a professional wall painter with 4 years of experience specializing in damp-proofing, wall waterproofing, and premium interior finish coats.',
    experienceYears: 4,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '300.00',
    isAvailable: true,
    serviceCities: ['Parwanoo', 'Kalka', 'Solan'],
    paymentIdentifier: 'shaiv.sood@upi',
    password: 'Password123!',
    phone: '+919800000000',
    city: 'Parwanoo',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44FvWP.md.png',
  },
  {
    name: 'Rudar Attri',
    email: 'rudar.attri@chowkspot.com',
    category: 'Home Appliance Repair',
    bio: 'I am Rudar Attri, specializing in refrigerator cooling diagnostics, microwave board repairs, and automatic washing machine servicing with 6 years of expertise.',
    experienceYears: 6,
    rateType: 'FIXED' as const,
    baseRate: '700.00',
    isAvailable: true,
    serviceCities: ['Solan', 'Shimla', 'Kandaghat'],
    paymentIdentifier: 'rudar.attri@upi',
    password: 'Password123!',
    phone: '+919711111111',
    city: 'Solan',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Tushar Karwal',
    email: 'tushar.karwal@chowkspot.com',
    category: 'Car Mechanic',
    bio: 'I am Tushar Karwal, providing dependable on-site 4-wheeler breakdown support, brake tuning, engine oil changes, and general vehicle upkeep.',
    experienceYears: 8,
    rateType: 'HOURLY' as const,
    baseRate: '600.00',
    isAvailable: true,
    serviceCities: ['Shimla', 'Solan', 'Dharampur'],
    paymentIdentifier: 'tushar.karwal@upi',
    password: 'Password123!',
    phone: '+919722222222',
    city: 'Shimla',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44KUj2.md.jpg',
  },
  {
    name: 'Shivani Vedwall',
    email: 'shivani.vedwall@chowkspot.com',
    category: 'CCTV & Security Tech',
    bio: 'I am Shivani Vedwall, a security systems expert with 5 years of experience in CCTV camera deployments, NVR recording setups, and intercom integrations.',
    experienceYears: 5,
    rateType: 'FIXED' as const,
    baseRate: '850.00',
    isAvailable: true,
    serviceCities: ['Chandigarh', 'Mohali', 'Panchkula'],
    paymentIdentifier: 'shivani.vedwall@upi',
    password: 'Password123!',
    phone: '+919823232323',
    city: 'Chandigarh',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44u1zg.md.png',
  },
  {
    name: 'Shashank Rajput',
    email: 'shashank.rajput@chowkspot.com',
    category: 'Pest Control Specialist',
    bio: 'I am Shashank Rajput, offering professional anti-termite treatments, bed bug sanitization, and deep disinfection pest control solutions.',
    experienceYears: 6,
    rateType: 'FIXED' as const,
    baseRate: '1100.00',
    isAvailable: true,
    serviceCities: ['Kalka', 'Pinjore', 'Chandigarh'],
    paymentIdentifier: 'shashank.rajput@upi',
    password: 'Password123!',
    phone: '+919867676767',
    city: 'Kalka',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44fjtV.md.jpg',
  },
  {
    name: 'Vivek Dhiman',
    email: 'vivek.dhiman@chowkspot.com',
    category: 'Welder & Fabricator',
    bio: 'I am Vivek Dhiman, a master metal fabricator with 9 years of experience in structural shed building, security gate construction, and grill welding.',
    experienceYears: 9,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '550.00',
    isAvailable: true,
    serviceCities: ['Baddi', 'Nalagarh', 'Barotiwala'],
    paymentIdentifier: 'vivek.dhiman@upi',
    password: 'Password123!',
    phone: '+919889898989',
    city: 'Baddi',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44TEKl.md.jpg',
  },
  {
    name: 'Sumit Chhalotre',
    email: 'sumit.chhalotre@chowkspot.com',
    category: 'Masonry & Brickwork',
    bio: 'I am Sumit Chhalotre, providing expert tile laying, granite installations, plastering, and general masonry repair services with 7 years of field experience.',
    experienceYears: 7,
    rateType: 'HOURLY' as const,
    baseRate: '450.00',
    isAvailable: true,
    serviceCities: ['Nalagarh', 'Baddi', 'Parwanoo'],
    paymentIdentifier: 'sumit.chhalotre@upi',
    password: 'Password123!',
    phone: '+919723232323',
    city: 'Nalagarh',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44qlbR.md.jpg',
  },
  {
    name: 'Vansh Vadhwa',
    email: 'vansh.vadhwa@chowkspot.com',
    category: 'Electrician',
    bio: 'I am Vansh Vadhwa, an electrician with 4 years of experience handling residential lighting, fan installations, and distribution board wiring.',
    experienceYears: 4,
    rateType: 'HOURLY' as const,
    baseRate: '350.00',
    isAvailable: true,
    serviceCities: ['Chandigarh', 'Mohali', 'Zirakpur'],
    paymentIdentifier: 'vansh.vadhwa@upi',
    password: 'Password123!',
    phone: '+919745454545',
    city: 'Chandigarh',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44nVqB.md.jpg',
  },
  {
    name: 'Shamb',
    email: 'shamb@chowkspot.com',
    category: 'Plumber',
    bio: 'I am Shamb, specializing in fixing stubborn leaks, bathroom pipe remodeling, and water purifier installations with 5 years of trusted local service.',
    experienceYears: 5,
    rateType: 'FIXED' as const,
    baseRate: '500.00',
    isAvailable: true,
    serviceCities: ['Mohali', 'Chandigarh', 'Kharar'],
    paymentIdentifier: 'shamb@upi',
    password: 'Password123!',
    phone: '+919756565656',
    city: 'Mohali',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44CNol.jpg',
  },
  {
    name: 'Jashan Sharma',
    email: 'jashan.sharma@chowkspot.com',
    category: 'Carpenter',
    bio: 'I am Jashan Sharma, offering custom woodwork, door mechanism repairs, and modular furniture maintenance with 6 years of professional dedication.',
    experienceYears: 6,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '300.00',
    isAvailable: true,
    serviceCities: ['Parwanoo', 'Kalka', 'Chandigarh'],
    paymentIdentifier: 'jashan.sharma@upi',
    password: 'Password123!',
    phone: '+919767676767',
    city: 'Parwanoo',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/C44Bkva.md.jpg',
  },
];
