export const SEED_CITIES = [
  // --- Loved Immediate Hubs (Parwanoo & Regional Belt) ---
  'Parwanoo',
  'Chandigarh',
  'Mohali',
  'Panchkula',
  'Kalka',
  'Pinjore',
  'Baddi',
  'Shimla',

  // --- Himachal Pradesh Belt ---
  'Solan',
  'Nalagarh',
  'Dharampur',
  'Kandaghat',
  'Barotiwala',
  'Waknaghat',
  'Subathu',
  'Dagshai',
  'Kasauli',
  'Chail',
  'Bilaspur',
  'Mandi',
  'Kullu',
  'Manali',
  'Dharamshala',
  'Kangra',
  'Palampur',
  'Hamirpur',
  'Una',
  'Nahan',
  'Paonta Sahib',
  'Sundernagar',
  'Chamba',

  // --- Tricity Satellites & Punjab Belt ---
  'Zirakpur',
  'Dera Bassi',
  'Kharar',
  'Landran',
  'New Chandigarh',
  'Kurali',
  'Ropar (Rupnagar)',
  'Patiala',
  'Ludhiana',
  'Jalandhar',
  'Amritsar',
  'Bathinda',
  'Pathankot',
  'Hoshiarpur',
  'Phagwara',
  'Rajpura',
  'Fatehgarh Sahib',
  'Mandi Gobindgarh',
  'Khanna',

  // --- Haryana Belt ---
  'Ambala Cantt',
  'Ambala City',
  'Yamunanagar',
  'Jagadhri',
  'Kurukshetra',
  'Karnal',
  'Panipat',
  'Sonipat',
  'Rohtak',
  'Hisar',
  'Sirsa',
  'Gurugram',
  'Faridabad',
  'Rewari',
  'Bahadurgarh',

  // --- Uttarakhand Belt ---
  'Dehradun',
  'Haridwar',
  'Rishikesh',
  'Roorkee',
  'Haldwani',
  'Rudrapur',
  'Kashipur',
  'Mussoorie',

  // --- Jammu & NCR North ---
  'Jammu',
  'Samba',
  'Kathua',
  'Udhampur',
  'Noida',
  'Greater Noida',
  'Ghaziabad',
] as const;

export const SEED_CATEGORIES = [
  // --- Everyday Local Trades & Skilled Services ---
  'Electrician',
  'Plumber',
  'Carpenter',
  'Painter',
  'Masonry & Brickwork',
  'Welder & Fabricator',
  'Key Maker & Locksmith',
  'Cobbler & Shoe Repair',
  'Tailor & Alterations',
  'Ironing & Pressing',
  'Handyman & Odd Jobs',
  'Glass & Window Repair',
  'Roofing & Waterproofing',
  'Flooring & Tiling',
  'Furniture Renovation',
  'Gutter & Drain Cleaner',

  // --- Daily Essentials, Utilities & Supplies ---
  'Milk Delivery Service',
  'Water Tanker Supplier',
  'Gas Cylinder Delivery',
  'Gas Stove Mechanic',
  'Newspaper Vendor',
  'Grocery Delivery Boy',
  'Vegetable & Fruit Vendor',
  'Tiffin & Home Food Service',
  'Waste & Scrap Collector (Raddiwalas)',

  // --- Home Maintenance, Appliance & Tech ---
  'Home Appliance Repair',
  'Bike & Scooter Mechanic',
  'Car Mechanic',
  'Car Wash & Detailing',
  'Cycle Mechanic',
  'Home Automation Tech',
  'Generator Mechanic',
  'HVAC & AC Service',
  'Mobile & Tablet Repair',
  'IT & Computer Support',
  'CCTV & Security Tech',
  'Solar Panel Installer',
  'Drone Operator & Tech',
  'Fire Safety Tech',
  'Web Development',
  'Graphic Design',
  'Social Media Helper',

  // --- Cleaning, Hygiene & Facility Services ---
  'Home Cleaning',
  'Carpet Cleaning',
  'Sofa Cleaning',
  'Curtain Cleaning',
  'Window Cleaning',
  'Water Tank Cleaning',
  'Pest Control Specialist',
  'Pressure Washing Specialist',
  'Laundry & Dry Cleaning',

  // --- Gardening, Landscaping & Agriculture ---
  'Gardener & Plant Care',
  'Landscaping Specialist',
  'Tree Pruning & Cutting',
  'Rooftop Garden Setup',

  // --- Caregiving, Wellness & Personal Grooming ---
  'Child Care & Nanny',
  'Elderly Care Assistant',
  'Pet Sitting & Dog Walker',
  'Pet Grooming Specialist',
  'Veterinary Assistant',
  'Fitness Trainer',
  'Yoga Instructor',
  'Dietician & Nutritionist',
  'Ayurveda Practitioner',
  'Massage Therapist',
  'Makeup Artist & Beautician',
  'Mehndi Artist',

  // --- Events, Ceremonies & Traditional Services ---
  'Pandit & Puja Specialist',
  'Vastu Consultant',
  'Astrologer',
  'Tent House Provider',
  'Catering Service',
  'Event Decorator',
  'Party & DJ Manager',
  'Wedding Planner Helper',
  'Photographer',
  'Videographer',

  // --- Education, Advisory & Moving ---
  'Home Tutor',
  'Career Counselor',
  'Legal Advisor',
  'Tax & GST Accountant',
  'Packers & Movers',
  'Car Transport Helper',
] as const;

export const SEED_USERS = [
  // --- Admin ---
  {
    name: 'Sharad Chandel',
    email: 'sharad@chowkspot.com',
    password: 'Password123!',
    phone: '+919876543210',
    city: 'Parwanoo',
    role: 'ADMIN' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },

  // --- Base Crew Service Providers ---
  {
    name: 'Smarth Sharda',
    email: 'smarth.sharda@chowkspot.com',
    password: 'Password123!',
    phone: '+919811111111',
    city: 'Chandigarh',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrGINTu.png',
  },
  {
    name: 'Rudar Partap Singh',
    email: 'rudar.partap@chowkspot.com',
    password: 'Password123!',
    phone: '+919822222222',
    city: 'Mohali',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrGAm3Q.png',
  },
  {
    name: 'Mohit Thakur',
    email: 'mohit.thakur@chowkspot.com',
    password: 'Password123!',
    phone: '+919833333333',
    city: 'Parwanoo',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrGYVoX.png',
  },
  {
    name: 'Bipin Awasthi',
    email: 'bipin.awasthi@chowkspot.com',
    password: 'Password123!',
    phone: '+919844444444',
    city: 'Kalka',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrGcljI.png',
  },
  {
    name: 'Anshul Katoch',
    email: 'anshul.katoch@chowkspot.com',
    password: 'Password123!',
    phone: '+919855555555',
    city: 'Shimla',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrMDZrl.th.png',
  },
  {
    name: 'Anshul Thakur',
    email: 'anshul.thakur@chowkspot.com',
    password: 'Password123!',
    phone: '+919866666666',
    city: 'Solan',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Rohan Chandel',
    email: 'rohan.chandel@chowkspot.com',
    password: 'Password123!',
    phone: '+919812121212',
    city: 'Baddi',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrVuhss.md.jpg',
  },
  {
    name: 'Kartik Kumar',
    email: 'kartik.kumar@chowkspot.com',
    password: 'Password123!',
    phone: '+919834343434',
    city: 'Parwanoo',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Sahil Vashisht',
    email: 'sahil.vashisht@chowkspot.com',
    password: 'Password123!',
    phone: '+919878787878',
    city: 'Solan',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrVzQdN.md.jpg',
  },
  {
    name: 'Sahil Akhtar',
    email: 'sahil.akhtar@chowkspot.com',
    password: 'Password123!',
    phone: '+919890909090',
    city: 'Panchkula',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrVdoSj.png',
  },
  {
    name: 'Tarun Kumawat',
    email: 'tarun.kumawat@chowkspot.com',
    password: 'Password123!',
    phone: '+919712121212',
    city: 'Baddi',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Gagan Bansal',
    email: 'gagan.bansal@chowkspot.com',
    password: 'Password123!',
    phone: '+919734343434',
    city: 'Kalka',
    role: 'WORKER' as const,
    avatarUrl: 'https://iili.io/CrVFDb4.png',
  },
  {
    name: 'Eshant Monga',
    email: 'eshant.monga@chowkspot.com',
    password: 'Password123!',
    phone: '+919856565656',
    city: 'Chandigarh',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },

  // --- Base Customers ---
  {
    name: 'Sachit Rajpal',
    email: 'sachit.rajpal@gmail.com',
    password: 'Password123!',
    phone: '+919877777777',
    city: 'Chandigarh',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Safal Varadhan',
    email: 'safal.varadhan@gmail.com',
    password: 'Password123!',
    phone: '+919888888888',
    city: 'Mohali',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Sachin Kumar Thakur',
    email: 'sachin.thakur@gmail.com',
    password: 'Password123!',
    phone: '+919899999999',
    city: 'Panchkula',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Shaiv Sood',
    email: 'shaiv.sood@gmail.com',
    password: 'Password123!',
    phone: '+919800000000',
    city: 'Parwanoo',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },
  {
    name: 'Rudar Attri',
    email: 'rudar.attri@gmail.com',
    password: 'Password123!',
    phone: '+919711111111',
    city: 'Solan',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Tushar Karwal',
    email: 'tushar.karwal@gmail.com',
    password: 'Password123!',
    phone: '+919722222222',
    city: 'Shimla',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Shivani Vedwall',
    email: 'shivani.vedwall@gmail.com',
    password: 'Password123!',
    phone: '+919823232323',
    city: 'Chandigarh',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/woman-a.jpg',
  },
  {
    name: 'Anju Rani',
    email: 'anju.rani@gmail.com',
    password: 'Password123!',
    phone: '+919845454545',
    city: 'Parwanoo',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/woman-a.jpg',
  },
  {
    name: 'Shashank Rajput',
    email: 'shashank.rajput@gmail.com',
    password: 'Password123!',
    phone: '+919867676767',
    city: 'Kalka',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Vivek Dhiman',
    email: 'vivek.dhiman@gmail.com',
    password: 'Password123!',
    phone: '+919889898989',
    city: 'Baddi',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Sumit Chhalotre',
    email: 'sumit.chhalotre@gmail.com',
    password: 'Password123!',
    phone: '+919723232323',
    city: 'Nalagarh',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Vansh Vadhwa',
    email: 'vansh.vadhwa@gmail.com',
    password: 'Password123!',
    phone: '+919745454545',
    city: 'Chandigarh',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Shamb',
    email: 'shamb@gmail.com',
    password: 'Password123!',
    phone: '+919756565656',
    city: 'Mohali',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },
  {
    name: 'Jashan Sharma',
    email: 'jashan.sharma@gmail.com',
    password: 'Password123!',
    phone: '+919767676767',
    city: 'Parwanoo',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Shruti Kumari',
    email: 'shruti.kumari@gmail.com',
    password: 'Password123!',
    phone: '+919778787878',
    city: 'Solan',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/woman-a.jpg',
  },
  {
    name: 'Harkiran Kaur',
    email: 'harkiran.kaur@gmail.com',
    password: 'Password123!',
    phone: '+919789898989',
    city: 'Mohali',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/woman-a.jpg',
  },
  {
    name: 'Ashu Singla',
    email: 'ashu.singla@gmail.com',
    password: 'Password123!',
    phone: '+919790909090',
    city: 'Panchkula',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
];

export const SEED_WORKER_PROFILES = [
  {
    email: 'smarth.sharda@chowkspot.com',
    category: 'Electrician',
    bio: 'Specialist in inverter wiring, smart switches, heavy load MCB installations, and commercial panel repairs.',
    experienceYears: 5,
    rateType: 'HOURLY' as const,
    baseRate: '400.00',
    isAvailable: true,
    serviceCities: ['Chandigarh', 'Mohali', 'Panchkula', 'Kalka', 'Parwanoo'],
    paymentIdentifier: 'smarth.sharda@upi',
  },
  {
    email: 'rudar.partap@chowkspot.com',
    category: 'Plumber',
    bio: 'High-pressure plumbing, underground pipe leak detection, bathroom sanitary fits, and water tank cleaning.',
    experienceYears: 6,
    rateType: 'FIXED' as const,
    baseRate: '600.00',
    isAvailable: true,
    serviceCities: ['Mohali', 'Chandigarh', 'Panchkula', 'Zirakpur'],
    paymentIdentifier: 'rudar.partap@okaxis',
  },
  {
    email: 'mohit.thakur@chowkspot.com',
    category: 'Carpenter',
    bio: 'Custom modular furniture, door lock fixes, wooden flooring, and emergency cabinet repairs.',
    experienceYears: 4,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '250.00',
    isAvailable: true,
    serviceCities: ['Parwanoo', 'Kalka', 'Pinjore', 'Solan'],
    paymentIdentifier: 'mohit.thakur@ybl',
  },
  {
    email: 'bipin.awasthi@chowkspot.com',
    category: 'Home Appliance Repair',
    bio: 'Washing machine motor replacement, microwave PCB fixes, and refrigerator gas charging.',
    experienceYears: 7,
    rateType: 'FIXED' as const,
    baseRate: '750.00',
    isAvailable: true,
    serviceCities: ['Kalka', 'Parwanoo', 'Panchkula', 'Pinjore'],
    paymentIdentifier: 'bipin.awasthi@paytm',
  },
  {
    email: 'anshul.katoch@chowkspot.com',
    category: 'Painter',
    bio: 'Interior waterproofing, dampness treatment, Royal texture painting, and exterior weather coats.',
    experienceYears: 5,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '300.00',
    isAvailable: true,
    serviceCities: ['Shimla', 'Solan', 'Kandaghat', 'Parwanoo'],
    paymentIdentifier: 'anshul.katoch@upi',
  },
  {
    email: 'anshul.thakur@chowkspot.com',
    category: 'Car Mechanic',
    bio: 'On-demand 4-wheeler & car emergency repairs, battery jumpstart, brake service, and oil changes.',
    experienceYears: 6,
    rateType: 'HOURLY' as const,
    baseRate: '500.00',
    isAvailable: true,
    serviceCities: ['Solan', 'Parwanoo', 'Dharampur', 'Kalka'],
    paymentIdentifier: 'anshul.thakur@sbi',
  },
  {
    email: 'rohan.chandel@chowkspot.com',
    category: 'Generator Mechanic',
    bio: 'Heavy industrial generator maintenance, motor starter repairs, and factory backup wiring.',
    experienceYears: 6,
    rateType: 'HOURLY' as const,
    baseRate: '650.00',
    isAvailable: true,
    serviceCities: ['Baddi', 'Nalagarh', 'Parwanoo', 'Barotiwala'],
    paymentIdentifier: 'rohan.chandel@icici',
  },
  {
    email: 'kartik.kumar@chowkspot.com',
    category: 'CCTV & Security Tech',
    bio: 'IP camera installation, biometric access systems, DVR/NVR configuration, and video doorbell setups.',
    experienceYears: 4,
    rateType: 'FIXED' as const,
    baseRate: '800.00',
    isAvailable: true,
    serviceCities: ['Parwanoo', 'Kalka', 'Solan', 'Chandigarh'],
    paymentIdentifier: 'kartik.kumar@paytm',
  },
  {
    email: 'eshant.monga@chowkspot.com',
    category: 'Solar Panel Installer',
    bio: 'Rooftop solar panel installation, hybrid inverter setup, tubular battery maintenance, and fault testing.',
    experienceYears: 5,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '450.00',
    isAvailable: true,
    serviceCities: ['Chandigarh', 'Mohali', 'Panchkula', 'Baddi'],
    paymentIdentifier: 'eshant.monga@upi',
  },
  {
    email: 'sahil.vashisht@chowkspot.com',
    category: 'Plumber',
    bio: 'Geyser installation, RO water purifier service, pipe fittings, and high-pressure motor pump fixes.',
    experienceYears: 3,
    rateType: 'FIXED' as const,
    baseRate: '350.00',
    isAvailable: true,
    serviceCities: ['Solan', 'Parwanoo', 'Shimla'],
    paymentIdentifier: 'sahil.vashisht@okaxis',
  },
  {
    email: 'sahil.akhtar@chowkspot.com',
    category: 'Pest Control Specialist',
    bio: 'Deep home sofa shampooing, full kitchen degreasing, termite treatment, and cockroach control.',
    experienceYears: 4,
    rateType: 'FIXED' as const,
    baseRate: '1200.00',
    isAvailable: true,
    serviceCities: ['Panchkula', 'Chandigarh', 'Mohali', 'Kalka'],
    paymentIdentifier: 'sahil.akhtar@ybl',
  },
  {
    email: 'tarun.kumawat@chowkspot.com',
    category: 'Welder & Fabricator',
    bio: 'Main gate welding, safety grill fabrication, tin shed creation, and balcony railing repairs.',
    experienceYears: 7,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '500.00',
    isAvailable: true,
    serviceCities: ['Baddi', 'Barotiwala', 'Nalagarh', 'Parwanoo'],
    paymentIdentifier: 'tarun.kumawat@upi',
  },
  {
    email: 'gagan.bansal@chowkspot.com',
    category: 'Masonry & Brickwork',
    bio: 'Granite countertop fitting, bathroom tile replacement, plastering, and brickwork maintenance.',
    experienceYears: 8,
    rateType: 'HOURLY' as const,
    baseRate: '400.00',
    isAvailable: false,
    serviceCities: ['Kalka', 'Pinjore', 'Parwanoo', 'Panchkula'],
    paymentIdentifier: 'gagan.bansal@sbi',
  },
];
