export const SEED_USERS = [
  // --- Core / Admin ---
  {
    name: 'Sharad Chandel',
    email: 'sharad@chowkspot.com',
    password: 'Password123!',
    phone: '+919876543210',
    city: 'Parwanoo',
    role: 'ADMIN' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },

  // --- Worker Crew (Service Providers across Himachal & Tricity) ---
  {
    name: 'Smarth Sharda',
    email: 'smarth.sharda@chowkspot.com',
    password: 'Password123!',
    phone: '+919811111111',
    city: 'Chandigarh',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Rudar Partap Singh',
    email: 'rudar.partap@chowkspot.com',
    password: 'Password123!',
    phone: '+919822222222',
    city: 'Mohali',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Mohit Thakur',
    email: 'mohit.thakur@chowkspot.com',
    password: 'Password123!',
    phone: '+919833333333',
    city: 'Parwanoo',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Bipin Awasthi',
    email: 'bipin.awasthi@chowkspot.com',
    password: 'Password123!',
    phone: '+919844444444',
    city: 'Kalka',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },
  {
    name: 'Anshul Katoch',
    email: 'anshul.katoch@chowkspot.com',
    password: 'Password123!',
    phone: '+919855555555',
    city: 'Shimla',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Anshul Thakur',
    email: 'anshul.thakur@chowkspot.com',
    password: 'Password123!',
    phone: '+919866666666',
    city: 'Solan',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Rohan Chandel',
    email: 'rohan.chandel@chowkspot.com',
    password: 'Password123!',
    phone: '+919812121212',
    city: 'Baddi',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Kartik Kumar',
    email: 'kartik.kumar@chowkspot.com',
    password: 'Password123!',
    phone: '+919834343434',
    city: 'Parwanoo',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Eshant Monga',
    email: 'eshant.monga@chowkspot.com',
    password: 'Password123!',
    phone: '+919856565656',
    city: 'Chandigarh',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },
  {
    name: 'Sahil Vashisht',
    email: 'sahil.vashisht@chowkspot.com',
    password: 'Password123!',
    phone: '+919878787878',
    city: 'Solan',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Sahil Akhtar',
    email: 'sahil.akhtar@chowkspot.com',
    password: 'Password123!',
    phone: '+919890909090',
    city: 'Panchkula',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Tarun Kumawat',
    email: 'tarun.kumawat@chowkspot.com',
    password: 'Password123!',
    phone: '+919712121212',
    city: 'Baddi',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Gagan Bansal',
    email: 'gagan.bansal@chowkspot.com',
    password: 'Password123!',
    phone: '+919734343434',
    city: 'Kalka',
    role: 'WORKER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },

  // --- Customers / Regular Users ---
  {
    name: 'Sachit Rajpal',
    email: 'sachit.rajpal@gmail.com',
    password: 'Password123!',
    phone: '+919877777777',
    city: 'Chandigarh',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Safal Varadhan',
    email: 'safal.varadhan@gmail.com',
    password: 'Password123!',
    phone: '+919888888888',
    city: 'Mohali',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Sachin Kumar Thakur',
    email: 'sachin.thakur@gmail.com',
    password: 'Password123!',
    phone: '+919899999999',
    city: 'Panchkula',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Shaiv Sood',
    email: 'shaiv.sood@gmail.com',
    password: 'Password123!',
    phone: '+919800000000',
    city: 'Parwanoo',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },
  {
    name: 'Rudar Attri',
    email: 'rudar.attri@gmail.com',
    password: 'Password123!',
    phone: '+919711111111',
    city: 'Solan',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Tushar Karwal',
    email: 'tushar.karwal@gmail.com',
    password: 'Password123!',
    phone: '+919722222222',
    city: 'Shimla',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Shivani Vedwall',
    email: 'shivani.vedwall@gmail.com',
    password: 'Password123!',
    phone: '+919823232323',
    city: 'Chandigarh',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/woman-a.jpg',
  },
  {
    name: 'Anju Rani',
    email: 'anju.rani@gmail.com',
    password: 'Password123!',
    phone: '+919845454545',
    city: 'Parwanoo',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/woman-a.jpg',
  },
  {
    name: 'Shashank Rajput',
    email: 'shashank.rajput@gmail.com',
    password: 'Password123!',
    phone: '+919867676767',
    city: 'Kalka',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Vivek Dhiman',
    email: 'vivek.dhiman@gmail.com',
    password: 'Password123!',
    phone: '+919889898989',
    city: 'Baddi',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Sumit Chhalotre',
    email: 'sumit.chhalotre@gmail.com',
    password: 'Password123!',
    phone: '+919723232323',
    city: 'Nalagarh',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/bicycle.jpg',
  },
  {
    name: 'Vansh Vadhwa',
    email: 'vansh.vadhwa@gmail.com',
    password: 'Password123!',
    phone: '+919745454545',
    city: 'Chandigarh',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
  {
    name: 'Shamb',
    email: 'shamb@gmail.com',
    password: 'Password123!',
    phone: '+919756565656',
    city: 'Mohali',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/boy-snow-hoodie.jpg',
  },
  {
    name: 'Jashan Sharma',
    email: 'jashan.sharma@gmail.com',
    password: 'Password123!',
    phone: '+919767676767',
    city: 'Parwanoo',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/kitchen-bar.jpg',
  },
  {
    name: 'Shruti Kumari',
    email: 'shruti.kumari@gmail.com',
    password: 'Password123!',
    phone: '+919778787878',
    city: 'Solan',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/woman-a.jpg',
  },
  {
    name: 'Harkiran Kaur',
    email: 'harkiran.kaur@gmail.com',
    password: 'Password123!',
    phone: '+919789898989',
    city: 'Mohali',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/woman-a.jpg',
  },
  {
    name: 'Ashu Singla',
    email: 'ashu.singla@gmail.com',
    password: 'Password123!',
    phone: '+919790909090',
    city: 'Panchkula',
    role: 'USER' as const,
    avatarUrl:
      'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man.jpg',
  },
];

export const SEED_WORKER_PROFILES = [
  {
    email: 'smarth.sharda@chowkspot.com',
    category: 'Electrician',
    bio: 'Specialist in inverter wiring, smart switches, heavy load MCB installations, and commercial panel repairs.',
    experienceYears: 5,
    rateType: 'HOURLY' as const,
    baseRate: '400.00',
    isAvailable: true,
    serviceCities: ['Chandigarh', 'Mohali', 'Panchkula', 'Kalka', 'Parwanoo'],
    paymentIdentifier: 'smarth.sharda@upi',
  },
  {
    email: 'rudar.partap@chowkspot.com',
    category: 'Plumber',
    bio: 'High-pressure plumbing, underground pipe leak detection, bathroom sanitary fits, and water tank cleaning.',
    experienceYears: 6,
    rateType: 'FIXED' as const,
    baseRate: '600.00',
    isAvailable: true,
    serviceCities: ['Mohali', 'Chandigarh', 'Panchkula', 'Zirakpur'],
    paymentIdentifier: 'rudar.partap@okaxis',
  },
  {
    email: 'mohit.thakur@chowkspot.com',
    category: 'Carpenter',
    bio: 'Custom modular furniture, door lock fixes, wooden flooring, and emergency cabinet repairs.',
    experienceYears: 4,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '250.00',
    isAvailable: true,
    serviceCities: ['Parwanoo', 'Kalka', 'Pinjore', 'Solan'],
    paymentIdentifier: 'mohit.thakur@ybl',
  },
  {
    email: 'bipin.awasthi@chowkspot.com',
    category: 'AC & Appliance Technician',
    bio: 'Foam jet AC servicing, PCB repairs, gas leak charging, and washing machine motor replacement.',
    experienceYears: 7,
    rateType: 'FIXED' as const,
    baseRate: '750.00',
    isAvailable: true,
    serviceCities: ['Kalka', 'Parwanoo', 'Panchkula', 'Pinjore'],
    paymentIdentifier: 'bipin.awasthi@paytm',
  },
  {
    email: 'anshul.katoch@chowkspot.com',
    category: 'Painter',
    bio: 'Interior waterproofing, dampness treatment, Royal texture painting, and exterior weather coats.',
    experienceYears: 5,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '300.00',
    isAvailable: true,
    serviceCities: ['Shimla', 'Solan', 'Kandaghat', 'Parwanoo'],
    paymentIdentifier: 'anshul.katoch@upi',
  },
  {
    email: 'anshul.thakur@chowkspot.com',
    category: 'Mechanic & Auto Expert',
    bio: 'On-demand 2-wheeler & car emergency repairs, battery jumpstart, brake service, and oil changes.',
    experienceYears: 6,
    rateType: 'HOURLY' as const,
    baseRate: '500.00',
    isAvailable: true,
    serviceCities: ['Solan', 'Parwanoo', 'Dharampur', 'Kalka'],
    paymentIdentifier: 'anshul.thakur@sbi',
  },
  {
    email: 'rohan.chandel@chowkspot.com',
    category: 'Industrial Electrician',
    bio: 'Heavy industrial electrical wiring, motor starter repairs, factory panel wiring, and generator setups.',
    experienceYears: 6,
    rateType: 'HOURLY' as const,
    baseRate: '650.00',
    isAvailable: true,
    serviceCities: ['Baddi', 'Nalagarh', 'Parwanoo', 'Barotiwala'],
    paymentIdentifier: 'rohan.chandel@icici',
  },
  {
    email: 'kartik.kumar@chowkspot.com',
    category: 'CCTV & Security Specialist',
    bio: 'IP camera installation, biometric access systems, DVR/NVR configuration, and video doorbell setups.',
    experienceYears: 4,
    rateType: 'FIXED' as const,
    baseRate: '800.00',
    isAvailable: true,
    serviceCities: ['Parwanoo', 'Kalka', 'Solan', 'Chandigarh'],
    paymentIdentifier: 'kartik.kumar@paytm',
  },
  {
    email: 'eshant.monga@chowkspot.com',
    category: 'Solar & Inverter Technician',
    bio: 'Rooftop solar panel installation, hybrid inverter setup, tubular battery maintenance, and fault testing.',
    experienceYears: 5,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '450.00',
    isAvailable: true,
    serviceCities: ['Chandigarh', 'Mohali', 'Panchkula', 'Baddi'],
    paymentIdentifier: 'eshant.monga@upi',
  },
  {
    email: 'sahil.vashisht@chowkspot.com',
    category: 'Plumber',
    bio: 'Geyser installation, RO water purifier service, pipe fittings, and high-pressure motor pump fixes.',
    experienceYears: 3,
    rateType: 'FIXED' as const,
    baseRate: '350.00',
    isAvailable: true,
    serviceCities: ['Solan', 'Parwanoo', 'Shimla'],
    paymentIdentifier: 'sahil.vashisht@okaxis',
  },
  {
    email: 'sahil.akhtar@chowkspot.com',
    category: 'Home Cleaning & Pest Control',
    bio: 'Deep home sofa shampooing, full kitchen degreasing, termite treatment, and cockroach control.',
    experienceYears: 4,
    rateType: 'FIXED' as const,
    baseRate: '1200.00',
    isAvailable: true,
    serviceCities: ['Panchkula', 'Chandigarh', 'Mohali', 'Kalka'],
    paymentIdentifier: 'sahil.akhtar@ybl',
  },
  {
    email: 'tarun.kumawat@chowkspot.com',
    category: 'Welder & Fabrication Expert',
    bio: 'Main gate welding, safety grill fabrication, tin shed creation, and balcony railing repairs.',
    experienceYears: 7,
    rateType: 'INSPECTION_FIRST' as const,
    baseRate: '500.00',
    isAvailable: true,
    serviceCities: ['Baddi', 'Barotiwala', 'Nalagarh', 'Parwanoo'],
    paymentIdentifier: 'tarun.kumawat@upi',
  },
  {
    email: 'gagan.bansal@chowkspot.com',
    category: 'Mason & Tiler',
    bio: 'Granite countertop fitting, bathroom tile replacement, plastering, and brickwork maintenance.',
    experienceYears: 8,
    rateType: 'HOURLY' as const,
    baseRate: '400.00',
    isAvailable: false,
    serviceCities: ['Kalka', 'Pinjore', 'Parwanoo', 'Panchkula'],
    paymentIdentifier: 'gagan.bansal@sbi',
  },
];
